---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-testing
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-issues
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/apeschel/flux-issues.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-issues
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-issues
  path: ./sops/replacements
  prune: true
  targetNamespace: flux-testing
